services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

# propel repositories

    propel.account_repository:
      class: Repositories\Propel\AccountRepository
      arguments: ['@propel_manager']

# PDO repositories

    pdo.account_repository:
       class: Repositories\PDO\AccountRepository
       arguments: ['@pdo_manager']
