# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        account_provider:
            id: account_provider
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

    encoders:
         #admin in_memory
         Symfony\Component\Security\Core\User\User: plaintext
         #regular account
         AppBundle\Database\Propel\Model\Account:
             algorithm: sha256
             encode_as_base64: false
             iterations: 1
    role_hierarchy:
         ROLE_USER: ROLE_USER
         ROLE_ADMIN: [ ROLE_USER, ROLE_ADMIN ]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin*
            provider: in_memory
            http_basic: true
        main:
            pattern: ^/*
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                use_referer: true
            logout:
                path: logout
                target: login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }