parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

#    propel.customer_repository:
#      class: Repositories\Propel\CustomerRepository
#      public: false
#
#    customer_fetcher:
#      class: Services\Customer\CustomerFetcher
#      arguments: ["@propel.customer_repository"]