imports:
    - { resource: "@AppBundle/Services/config/services.yml" }
    - { resource: "@AppBundle/Repositories/config/repositories.yml" }

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

#AppBundle\:
#     resource: '../../src/AppBundle/*'
#     exclude: '../../src/AppBundle/Repositories'

# PDO
    pdo_wrapper:
        public: false
        class: AppBundle\Database\PDO\Manager\PDOWrapper
        arguments:
             - '%database_host%'
             - '%database_name%'
             - '%database_user%'
             - '%database_password%'
             - '%database_charset%'

    pdo_manager:
        class: AppBundle\Database\PDO\Manager\PDOManager
        arguments: ['@pdo_wrapper']

# propel
    propel_manager:
        class: AppBundle\Database\Propel\Manager\ModelManager