imports:
    - { resource: security.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

# account
    email_unique_validator:
        class: AppBundle\Form\Validators\EmailUniqueValidator
        arguments: ['@account_fetcher']

    account_fetcher:
      class: AppBundle\Services\Account\AccountFetcher
      arguments: ["@pdo.account_repository"]