services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    customer_fetcher:
      class: Services\Customer\CustomerFetcher
      arguments: ["@propel.customer_repository"]