# user login/registration

register:
    path:     /register
    defaults: { _controller: AppBundle:Security\Register:index }

login:
    path:     /login
    defaults: { _controller: AppBundle:Security\Login:index }

login_check:
    path:     /login_check

logout:
    path:     /logout

# pages

homepage:
    path:     /
    defaults: { _controller: AppBundle:Homepage\Homepage:index }

# api

accounts:
    path:    /accounts
    defaults: { _controller: AppBundle:Api\Accounts\Accounts:index }
