services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

# propel repositories

    propel.account_repository:
      class: AppBundle\Repositories\Propel\AccountRepository
      arguments: ['@propel_manager']

    propel.product_repository:
      class: AppBundle\Repositories\Propel\ProductRepository
      arguments: ['@propel_manager']

# PDO repositories

    pdo.account_repository:
       class: AppBundle\Repositories\PDO\AccountRepository
       arguments: ['@pdo_manager']

    pdo.product_repository:
       class: AppBundle\Repositories\PDO\ProductRepository
       arguments: ['@pdo_manager']
